const suggestions = [
  "The Shawshank Redemption",
  "The Godfather",
  "The Dark Knight",
  "The Godfather 2",
  "12 Angry Men",
  "Schindler's List",
  "The Lord of The Rings: The Return of the King",
  "Pulp Fiction",
  "The Lord of The Rings: The Fellowship of the Ring",
  "The Good, The Bad and The Ugly",
  "Forrst Gump",
  "The Lord of The Rings: The Two Towers",
  "Fight Club",
  "Inception",
  "Star Wars",
  "The Matrix",
  "Goodfellas",
  "One Flew Over The Cuckoo's Nest",
  "Se7en",
  "Interstellar",
  "It's a Wonderfull Life",
  "Seven Samurai",
  "The Silence of the Lambs",
  "Saving Private Ryan",
  "City of God",
];

export { suggestions };
