const STATIC_RESOURCES = [
  "/",
  "/fallback.html",
  "./assets/images/favicon.png",
  "./style/fallback.css",
  "./style/index.css",
  "./style/main.css",
  "./style/mobile.css",
  "./style/snackbar.css",
  "./style/tablet.css",
  "./js/app.js",
  "./js/form.js",
  "./js/index.js",
  "./manifest.json",
  "./assets/images/img_512.png",
];
